version: '3.3'
services:
    promtail:
        container_name: promtail
        volumes:
            - '/opt/docker/promtail:/etc/promtail'
            - '/var/log:/opt/var/log:ro'
            - '/var/lib/docker/containers:/opt/var/lib/docker/containers:ro'
        image: 'grafana/promtail:main'
        restart: always
